version: '3'

services:
  mongo:
    image: mongo
    restart: always
    env_file: ./.env
    volumes:
      - type: volume
        source: "mongo-store"
        target: "/data/db"
      - type: volume
        source: "mongo-store-config"
        target: "/data/configdb"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:?err}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:?err}
  frontend:
    image: node:18-bullseye-slim
    env_file: ./.env
    environment:
      DB_URL: ${DB_URL:?err}
      NEXTAUTH_URL: ${NEXTAUTH_URL:?err}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:?err}
      OAUTH_CLINTID: ${OAUTH_CLIENTID:?err}
      OAUTH_SECRET: ${OAUTH_SECRET:?err}
    volumes:
      - type: bind
        source: "./frontend"
        target: "/app"
      - node_modules_volume:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    working_dir: /app
    command: bash -c "npm install && npx next dev"

volumes:
  mongo-store:
  mongo-store-config:
  node_modules_volume:
